name = "imagisplus"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = "https://known-ibex-53011.upstash.io"
UPSTASH_REDIS_REST_URL = "Ac8TAAIjcDE4OTcwMmMyMWNlOWQ0NTAyODMyZWMxNTUzODM3YTcwM3AxMA"